steps:
- name: "golangci/golangci-lint"
  entrypoint: "golangci-lint"
  args: ["run", "-v"]
- name: "golang:1.13"
  entrypoint: "go"
  args: ["test", "-v", "./..."]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
